### ISSUE TITLE
[BUG] Installer eating up memory

### ISSUE THREAD

**Issue by foxmike80** [flybywiresim/installer#106]
**Installer Version**
latest from 15.1.2021

**Describe the bug**

Even when the installer is closed it remains active and eats up an incredible amount memory (>25GB).

**To Reproduce**

1. Run installer
2. Close it again
3. Watch memory usage increase over time
![image](https://user-images.githubusercontent.com/76132268/104734779-0dbe5400-5741-11eb-8d63-690641fb2753.png)

**Expected behavior**

close the application when exiting

**Additional context**

Discord username (if different from GitHub):

**Comment by Tawmu** [comment]
Can also confirm - just found it sitting in the background at 25GB RAM and going up.

**Comment by Benjozork** [comment]
Seems to only happen when the installer is closed.

Looks like some background process is involved or as if the electron/chrome process is not terminated properly

**Comment by nistei** [comment]
@foxmike80 Can you confirm that this issue has been fixed after updating?

**Comment by foxmike80** [comment]
Yepp, seems to be working. Great job! Thanks a lot.

**Comment by foxmike80** [comment]
Please re-open:
Issue seems to be back, it just happened again: 
![image](https://user-images.githubusercontent.com/76132268/107153999-c5c1d400-6970-11eb-9b18-88baa24c09ec.png)

Installer version is 1.0.4

**Comment by ZigTag** [comment]
Yeah the bug only occurs while updating the installer itself

**Comment by Benjozork** [comment]
Some more info

The zombie process is a chrome renderer process from an old version (in @nistei's case, 1.0.2).  Curiously, it seems like Squirrel did not remove that old version from `C:\Users\$USER\AppData\Local\fbw_installer`.

In my case, however it did. The zombie process being there therefore could be related to whether or not Squirrel deletes the old version.

**Comment by BrunerChris** [comment]
Happening to me as well on first install.

**Comment by Perondas** [comment]
Just had this happen to me 2 days in a row, where I din´t realize it and as the day went on my pc got less and less responsive.

**Comment by ternium1** [comment]
I can confirm, this is still happening to me (Up to 17GB of RAM before pc instability and apps starting to crash)
