### ISSUE TITLE
[BUG] Installer stuck on "Decompressing" 

### ISSUE THREAD

**Issue by dreiviertell** [flybywiresim/installer#110]
**Installer Version**

**Describe the bug**
When hitting the update or install button, the installation gets stuck and it just shows "Decompressing. Happens to all 3 Mainline versions.

**To Reproduce**
Try to install the mod via the installer

1.
2.
3.

**Expected behavior**
Just shows "Decompressing" and doesnt install the mod

Discord dreiviertel#7221
Thanks for your great work!

**Comment by Benjozork** [comment]
Being investigated right now

**Comment by Benjozork** [comment]
Was resolved by restarting the download proxy service
