### ISSUE TITLE
[BUG] installer dont update the mod

### ISSUE THREAD

**Issue by Stavroulis1985** [flybywiresim/installer#128]
**Installer Version**
1.04
**Describe the bug**

After the update the download isnt starting
**To Reproduce**

1.After the update from 1.03 to 1.04
2.
3.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ZigTag** [comment]
Please include more information

**Comment by Stavroulis1985** [comment]
When i updated the installer it isnt updating the mod.
it wont start the download to either version i choose.

**Comment by ZigTag** [comment]
Its working perfectly for me, are you sure you don't have a slow internet connection?

**Comment by Stavroulis1985** [comment]
yes i have 100mbit internet connection.
it was working very good unti it started the update from 1.03 to 1.04 and after the restart it isnt starting the updates.

**Comment by nistei** [comment]
We have completely reworked the download logic for the new versions. Closing this. Please create a new issue if this happens with versions >= v1.1.0
