### ISSUE TITLE
[REQUEST] Downgrade/install older versions

### ISSUE THREAD

**Issue by racer01** [flybywiresim/installer#143]
**Is your feature request related to a problem? Please describe.**

Asobo released the flaps hotfix so I wanted to downgrade the a32nx to an older version which doesn't have the flaps fix but clicking the versions only opened the changelog (which was unexpected for me).

**Describe the feature you'd like to see implemented**

Clicking the version numbers on the left under "Version history" should install that version of the mod. Changelog can have a separate button named changelog under the date (this would help to "advertise" the changelog can be opened from the installer which I didn't know).

**Additional context**

Discord username (if different from GitHub): racer01#4657

**Comment by Benjozork** [comment]
FYI, we made an announcement on our social media and discord that the hotfix was reverted in the latest development and experimental versions.

**Comment by FoxtrotSierra6829** [comment]
We won't support downgrading, since old versions might not be compatible at all to newer MSFS versions. Fixes are always available very quickly after the MSFS update, and it's very rare that old versions work better than newer after an update.
