### ISSUE TITLE
[BUILD] Remove old CDN from release workflow

### ISSUE THREAD

**Issue by nistei** [flybywiresim/installer#162]
After the release of v1.1.0, all users will have an installer pulling from the new CDN. We can then remove the upload of newer versions to the old CDN without breaking any updates.

Discord username (if different from GitHub): nistei#1362

**Comment by FoxtrotSierra6829** [comment]
Leave enough time in between, so even if someone doesn't update the mod very often and the installer isn't running because of this, he gets the update without completely redownloading

**Comment by nistei** [comment]
All old patch files are available on Bunny as well. Newer ones won't be available on DigitalOcean with v1.1 being the last one. The only impact a user would have is that in order to update to the newest version it needs to be done in 2 steps (to newest state on DO then to newest state on Bunny). Since our installer forces users to update they should all be on the most recent version where the update is done in a single step.

**Comment by FoxtrotSierra6829** [comment]
Just wanted to make sure 1.1 is available on DO for some time

**Comment by nistei** [comment]
It will. This is only a change in the build process. v1.1 will remain available on DO for a currently undefined amount of time. At least multiple months.

**Comment by Benjozork** [comment]
When can this be done
