### ISSUE TITLE
Cannot Installed if a `#` or a other allowed character can be found in the used user name for win10

### ISSUE THREAD

**Issue by MirkoBrunner** [flybywiresim/installer#165]
**Installer Version**
- unknown (Installer downloaded at: 2021-03-14)

**Describe the bug**
Immediately after starting the installer, it will stop at a black window. Nothing more happens. This will be happen if you have an allowed special character in your OS (Windows 10) user name. Yes i know other one that has problems with it.

the nice black window:
<img width="1108" alt="bug_pic_1" src="https://user-images.githubusercontent.com/1172356/111235699-7ca91380-85f1-11eb-84d6-21f533b0c54a.png">

**To Reproduce**
1. Create a new user account on windows 10 with the special character `#` (or similar if allowed from the system (not allowed are: `" / \ [ ] : ; | = , + * ? < >`)) in the name
2. Download the newest version
3. Start the installer

**Expected behavior**
Hmm that the installer works as expected ;)

**Additional context**
I'm a developer and I know that this is a very very special case... and it is difficult to fix it ;) This problem will be happen with some third party file system libraries there are build for multiple platforms (or not?).

Discord: SlaughterMan#3066 (mostly aviable after UTC 18:00)

**Comment by nistei** [comment]
Windows...

**Comment by FoxtrotSierra6829** [comment]
In case you still have the same configuration on your machine, could you test if the issue still exists with the update from yesterday?

**Comment by MirkoBrunner** [comment]
Yeah it works! THANKS! :D

> In case you still have the same configuration on your machine, could you test if the issue still exists with the update from yesterday?
