### ISSUE TITLE
Current A320nx installed version is not the one that is selected when running the installer anymore

### ISSUE THREAD

**Issue by cadilhac** [flybywiresim/installer#176]
**Installer Version**

1.1.0

**Describe the bug**
Previsouly, the installer was remembering the latest installed version (stable, dev, custom), or at least the selected option when leaving it. Now, stable is always selected when launching the app. This is a pity because it was a way to remember which version is currently installed.

**Comment by FoxtrotSierra6829** [comment]
I believe you didn't update yet since you are on 1.1.0. If so, it's a totally normal behavior

**Comment by cadilhac** [comment]
ok, so not sure if it auto-updated, but what I know is that before yesterday, if Dev was the installed version then Dev was the initially selected option when running the installer. Moreover, when selecting another version, the button was changing from Installed or Update to Switch. Now it's not the case anymore. The button always show Install. Also I had no warning popup when selecting Custom FBW.

**Comment by FoxtrotSierra6829** [comment]
Now I strongly believe you didn't update the mod since you are on 1.1.0. Your described behavior is correct then until you re-install any version

**Comment by cadilhac** [comment]
Why do I have to reinstall the mod? It's already there, as usual since the first time I used the installer. Note that the installation folder never changed.

**Comment by FoxtrotSierra6829** [comment]
We're switching to a modular system where it doesn't download every file again when there is an update available. The old installs are not compatible with this system.

**Comment by cadilhac** [comment]
Ok, thanks, got it. Will reinstall the mod.

**Comment by cadilhac** [comment]
Reinstalled it. It worked. But later today, there was an update. It downloaded something very fast and I then get an error message "Failed to install" (with version 1.1.1).

**Comment by FoxtrotSierra6829** [comment]
try deleting `flybywire-aircraft-a320-neo` in your community folder and reinstall again

**Comment by cadilhac** [comment]
Will do and will check for the next update.

**Comment by cadilhac** [comment]
Unfortunately, after trying all this, still doesn't work and I get a "Failed to install" message when updating.

**Comment by FoxtrotSierra6829** [comment]
But that does only occur if it's not a clean installation?

**Comment by cadilhac** [comment]
Well, I did a clean installation already. It reoccurs after that if there is an update.

**Comment by FoxtrotSierra6829** [comment]
Okay please look if there is any relation to #179 or #181

**Comment by cadilhac** [comment]
Same as #181
