### ISSUE TITLE
La tablette ne s'affiche pas dans l'A320NX

### ISSUE THREAD

**Issue by Draconic112** [flybywiresim/installer#198]
**0.5.4**

**La tablette dans le cockpit a gauche ne s'affiche pas**

**To Reproduce**

1. Installler l'installer officiel
2. Créer un plan de vol directement dans Flight Simulator
3. Spawn n'importe où en Cold and Dark

**La tablette devrait s'afficher et être fonctionnelle**

**La tablette ne s'afiche pas du tout**

**![image](https://user-images.githubusercontent.com/54067295/112715944-bf1cfb00-8ee3-11eb-968e-7ba9e827f540.png)**

**Additional context**

Was this working before/when did the issue start occurring?
No

Is this a problem in the vanilla unmodded game?
No

Discord username (if different from GitHub): Draconic_112#8329

**Comment by ternium1** [comment]
Sorry, as he was speaking french, I answered in french to be more understandable...

**Comment by MisterChocker** [comment]
So for non french speaking people, whats the issue?

**Comment by ternium1** [comment]
He said that the EFB didn't work using the Stable branch, I told him that it was normal as the EFB is not yet implemented on the Stable branch, and told him to switch to the Development branch, as it is more stable since the Sim update of March and there is the EFB working.

**Comment by Draconic112** [comment]
Yes, thanks for the awnser ! As you can see, my english is not very good... That's why i wrote in french :-)

**Comment by MisterChocker** [comment]
Thanks for lettings us know.
