### ISSUE TITLE
[REQUEST] Show warning / error if not enough storage is availaible

### ISSUE THREAD

**Issue by JOKUE2002** [flybywiresim/installer#199]
**Is your feature request related to a problem? Please describe.**

Whilst installing an update, I managed to fill the capacity of my ssd to 100%, which led to some weird graphics glitches in the sim (labels of buttons not shown, whole cockpit white).

**Describe the feature you'd like to see implemented**

A warning, that blocks the update / installation if the disk space is not enough (I had around 0.5GB left which wasn't enough.

**Additional context**

An error message, which shows the installation failed would be helpful as well...

Discord username (if different from GitHub): JOKUE2002

**Comment by Benjozork** [comment]
This is done.
