### ISSUE TITLE
Switching: Development -> Stable ERROR: Retrying livery module

### ISSUE THREAD

**Issue by IIIISEIIII** [flybywiresim/installer#216]
![Retrying-livery-module-Error](https://user-images.githubusercontent.com/82036424/113712404-5e14d480-96e6-11eb-8abc-cf295ae3a43b.png)

Hi Guys,

when Switching from Development to Stable version I got this Error message in the FlyByWireInstaller: Retrying livery module (it loads again livery textures and then says the error again for a few times).

When loading the plane in MSFS all the annunciator lights are lit up and no button can be switched. Whereas the outside of the plane looks fine.

What can I do to get flying again?

Thanks so much!
Simon

**Comment by IIIISEIIII** [comment]
Here is what fixed it for me: 
1. removed everything A320 FlyByWire-related in my FS2020 community folder
2. I run the installer to install FlyByWire Mod version of choice (e.g. stable) again
3. enjoying life

**Comment by ZigTag** [comment]
I think this will be fixed in v0.6 because I don't think the livery module exists in the stable version (needs citation)

**Comment by nistei** [comment]
> I think this will be fixed in v0.6 because I don't think the livery module exists in the stable version (needs citation)

It does exist and shouldn't cause any issues. Fragmenter is designed to add and remove modules dynamically.

**Comment by nistei** [comment]
Interestingly, for users with this issue (4-5%) the download of the module also fails when downloading through Chrome or Firefox.
