### ISSUE TITLE
[BUG] Updating the airplane causes mod to not be installed 

### ISSUE THREAD

**Issue by uzytkownik** [flybywiresim/installer#227]
**Installer Version**
1.1.4

**Describe the bug**
After update or switch of version A320 go backs to vanilla version

**To Reproduce**
1. Install mod via installer
2. Verify that it is working
3. Update mod or switch to experimental stable version

**Expected behavior**
An updated version is used instead of vanilla.

**Additional context**
Removing mod manually and installing from scratch fixes the issue. I use steam version of MSFS

**Comment by FoxtrotSierra6829** [comment]
Can you elaborate more on what exactly indicates it is not installed anymore?

**Comment by uzytkownik** [comment]
For example air condition and ADRIS is inoperable and on board computer does not open on MCDU MENU.

**Comment by FoxtrotSierra6829** [comment]
Did you select the FlyByWire A320neo?

**Comment by uzytkownik** [comment]
I don't get it as separate aircraft? I only single A320neo.

**Comment by FoxtrotSierra6829** [comment]
So you're on stable?

**Comment by uzytkownik** [comment]
Hmm. That may be a feature not a bug than...

**Comment by FoxtrotSierra6829** [comment]
Only experimental and development version will show up as a separate aircraft, stable is still overriding the default A320neo until v0.6.0. The ADIRS should be operable anyways with all the three versions. Can you screenshot your community folder and your A32NX folder?
