### ISSUE TITLE
Installer locks up when finishing

### ISSUE THREAD

**Issue by franklw262** [flybywiresim/installer#228]
**Installer Version**latest
1.1.4
**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FoxtrotSierra6829** [comment]
please fill out the template, or your issue will be deleted

**Comment by franklw262** [comment]
Sorry very new to this where can I find the template 
Thanks

**Comment by FoxtrotSierra6829** [comment]
edit your post

**Comment by franklw262** [comment]
I cannot update the above

**Comment by FoxtrotSierra6829** [comment]
there is a pencil button

**Comment by FoxtrotSierra6829** [comment]
no response, closing
