### ISSUE TITLE
[REQUEST] Livery conversion search function

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/installer#235]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Some of us, like myself, may have installed alot of liveries for modelmatching in online networks (I do have 303 installed). As you usually dont want to convert all liveries for the FBW (only the ones you want to use) it might be a paint to scroll through the whole list of liveries to mark the ones you want. So a quick search function would be a nice to have. I would suggest putting it above the Cancel/Confirm buttons.
![image](https://user-images.githubusercontent.com/448627/114829821-d0af3f80-9dcb-11eb-886a-525270314499.png)

**Additional context**

Discord username (if different from GitHub):

**Comment by Benjozork** [comment]
Closing as this feature no longer exists.
