### ISSUE TITLE
Something went very werong on Installer Startup

### ISSUE THREAD

**Issue by 0x070E** [flybywiresim/installer#247]
Hello, i get the following error when launching the FBW Installier:

![image](https://user-images.githubusercontent.com/59081292/115570499-76781800-a2be-11eb-9c5b-d1a13205b26d.png)

![image](https://user-images.githubusercontent.com/59081292/115570624-8f80c900-a2be-11eb-8127-8e3882eb33ce.png)

**Comment by FoxtrotSierra6829** [comment]
Easiest thing is to just create that folder structure as a dummy, then change it manually in settings, and delete the created folder after if wanted. We are not just investigating and don't know how to fix. Additionally, if creating the folder is not possible, you can go into `%userprofile%\AppData\Roaming\FlyByWire Installer`, open `config.json` and change `"msfsPackagePath":` to `"C:\\"`, thereafter reconfigure in settings

**Comment by 0x070E** [comment]
> Easiest thing is to just create that folder structure as a dummy, then change it manually in settings, and delete the created folder after if wanted. We are not just investigating and don't know how to fix. Additionally, if creating the folder is not possible, you can go into `%userprofile%\AppData\Roaming\FlyByWire Installer`, open `config.json` and change `"msfsPackagePath":` to `"C:\\"`, thereafter reconfigure in settings

Thank you for the fast response, it worked pretty flawless after i just deleted the FBW Installer folder within the Appdata folder, a relaunch of the Installer was necessary afterwards,
