### ISSUE TITLE
[REQUEST] Implement changelog/ github closed PRs

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/installer#25]
**Is your feature request related to a problem? Please describe.**

The problem that I never know what changed :D

**Describe the feature you'd like to see implemented**

A changelog for the stable version and a page with recently closed PRs of the current milestone. 
Stable changelog: https://github.com/flybywiresim/a32nx/blob/master/.github/CHANGELOG.md
Master changelog: https://github.com/flybywiresim/a32nx/milestone/7?closed=1

It could be implemented via a small Linktext Below the download buttons, that opens either the website or an additional page in the installer (which i would prefer)

**References**

![image](https://user-images.githubusercontent.com/448627/102867200-b4604f00-4438-11eb-840c-eecf60edf647.png)

**Additional context**

Discord username (if different from GitHub): St54Kevin#3583

**Comment by Benjozork** [comment]
Figma design prototype

![image](https://user-images.githubusercontent.com/4503241/103117334-e8ee2980-4637-11eb-93e3-14e1e8ba31bc.png)

**Comment by St54Kevin** [comment]
> Figma design prototype
> 
> ![image](https://user-images.githubusercontent.com/4503241/103117334-e8ee2980-4637-11eb-93e3-14e1e8ba31bc.png)
> 

Yeah that's nice. Do you want the version number to be click able for the changelog?

**Comment by Benjozork** [comment]
> Do you want the version number to be click able for the changelog?

It is in my prototype implementation in #34

**Comment by nistei** [comment]
Fixed in #34

**Comment by St54Kevin** [comment]
> Fixed in #34 

That's not correct! No changelog for either dev or FBW version. Just stable

**Comment by nistei** [comment]
@St54Kevin You made a separate issue for that. See #76

**Comment by St54Kevin** [comment]
> @St54Kevin You made a separate issue for that. See #76 

Ups sorry :D
