### ISSUE TITLE
[BUG] Can not install if Packages directory moved

### ISSUE THREAD

**Issue by Dawen18** [flybywiresim/installer#250]
**Installer Version**
1.2.0

**Describe the bug**
I have moved the Package directory to another disk to free space on my C disk, and even with a link inside the LocalCache directory to the moved Packages directory, the installation throw an error

**To Reproduce**

1. Copy the `C:\Users\Your username\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages` directory to another disk drive
2. Modify the `C:\Users\Your username\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\UserCfg.opt` at the end to point to your new package directory
3. Verify that MSFS run correctly
4. Execute the installer

**Expected behavior**

Installation of the A32NX in the new directory

**Additional context**

Discord username (if different from GitHub):
discord username: Dawen#9026 (present in the FlyByWire discord)

![image](https://user-images.githubusercontent.com/7900740/117894717-44eedd00-b2bd-11eb-9d07-8896c2a44c6f.png)

**Comment by Benjozork** [comment]
Create the old directory, restart installer and change it to the new oen

**Comment by Benjozork** [comment]
Will be fixed in the next version

**Comment by Dawen18** [comment]
> Create the old directory, restart installer and change it to the new oen

Tanks a lot, it worked.
