### ISSUE TITLE
[BUG] INSERT TITLE HERE

### ISSUE THREAD

**Issue by ratingerpilot** [flybywiresim/installer#252]
Hello
the installer doesn't work anymore. it shows me an error when i want to update. is it a problem of the server or is it aproblem of my pc?
thank you !

**Installer Version**

**Describe the bug**

**To Reproduce**

1.
2.
3.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by FoxtrotSierra6829** [comment]
It's due to recent DNS malconfiguration and is already fixed. (for some people, to others it still takes some time)

**Comment by ratingerpilot** [comment]
ah ok.
thank you very much :)
