### ISSUE TITLE
UNINSTALL OPTION

### ISSUE THREAD

**Issue by ajts1958** [flybywiresim/installer#256]
I still don't have the airplane symbol on moving map, after what I think was a clean unistallation and installation

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

uninstall option to clean everything and allow a clean installation

**Additional context**

Discord username (if different from GitHub):

**BY REMOVING THIS LINE, I ATTEST THAT I HAVE FOLLOWED THE ISSUE TEMPLATE AND PROVIDED A TITLE, as well as searched for other possible duplicate issues. I acknowledge if this line is not removed and/or the issue template is not respected, my issue will be closed without warning**

**Comment by ChengJin-git** [comment]
Same here, an uninstall option would be great!

**Comment by GhostEagle68** [comment]
@ajts1958 @ChengJin-git It is being worked on iirc. No ETA yet.

**Comment by FoxtrotSierra6829** [comment]
duplicate of #229
