### ISSUE TITLE
[BUG] No such file or directory if configured folder is missing

### ISSUE THREAD

**Issue by Phil7789** [flybywiresim/installer#258]
**Installer Version**
1.2.0
**Describe the bug**
If the installation folder is moved or deleted and thus is missing the installer is not asking for a new folder but fails with an ENOENT error. The only available option is to close the installer.

**To Reproduce**
1. Set an installation path in the installer where the aircraft is being installed
2. Close the installer
2. Move, rename or delete the folder
3. With the next start the installer throws the ENOENT error

**Expected behavior**
The installer should warn that the set installation folder is missing and ask for a new folder or corrected path.

**Additional context (Workaround)**
1. Recreate the original path with empty folders (the path is given with the error)
2. Start the installer and reconfigure the setting to the actual installation path
3. Remove the empty temp folders

Discord username (if different from GitHub): Phil7789# 0191 (empty space is needed only here as GitHub is eating the 0)

![image](https://user-images.githubusercontent.com/21036064/121532702-e1f97e80-c9ff-11eb-8316-accdaf53c5b2.png)

**Comment by FoxtrotSierra6829** [comment]
known issue (see https://docs.flybywiresim.com/start/reported-issues/ ), fixed, but not shipped yet due to waiting on #205

**Comment by Phil7789** [comment]
Sorry, I only checked the open issues. My bad.
