### ISSUE TITLE
Please help. My installer keeps going wrong. what can I do to fix this.

### ISSUE THREAD

**Issue by MTAkid** [flybywiresim/installer#259]
**Installer Version**

**Describe the bug**

**To Reproduce**

1. It just appeared. I did not do anything.
2.
3.

**Expected behavior**

**Additional context**

Discord username (if different from GitHub):

![FlyByWire Installer 6_10_2021 7_34_20 PM](https://user-images.githubusercontent.com/85714071/121609954-f8650180-ca22-11eb-952c-edd52c836ecd.png)

**Comment by FoxtrotSierra6829** [comment]
duplicate of #258

**Comment by FoxtrotSierra6829** [comment]
https://docs.flybywiresim.com/start/reported-issues/#installer-issues
