### ISSUE TITLE
[REQUEST] Optimize space

### ISSUE THREAD

**Issue by St54Kevin** [flybywiresim/installer#26]
**Is your feature request related to a problem? Please describe.**

Space not used optimal

**Describe the feature you'd like to see implemented**

Optimize the space of the right side. The information text begins way too far at the bottom. The site could be used way more efficiently.

**References**

![image](https://user-images.githubusercontent.com/448627/102866637-df966e80-4437-11eb-8dfc-fbb1ea0bd752.png)

**Additional context**

Discord username (if different from GitHub): St54Kevin#3583

**Comment by St54Kevin** [comment]
Why is this closed? Its not solved

**Comment by tracernz** [comment]
@St54Kevin https://github.com/flybywiresim/installer/commit/25414382e3638c86c28db5dc773c5a95ef4907e1 should make it go 35% of the view height, up to a max of 400 pixels.

**Comment by St54Kevin** [comment]
> @St54Kevin https://github.com/flybywiresim/installer/commit/25414382e3638c86c28db5dc773c5a95ef4907e1 should make it go 35% of the view height, up to a max of 400 pixels.

Yeah it might not be in current release that's why I wondered
