### ISSUE TITLE
[BUG] A32NX is not installing

### ISSUE THREAD

**Issue by Askiz** [flybywiresim/installer#260]
**Installer Version**
Development 5f697b1
**Describe the bug**

So, it's just not installing. It's written "installed" ( and actually it's in game's files ) , but nothung happens in mfs2020
**To Reproduce**

1.  I've wanted to play mfs and when i openede the game, there was nothing, that goes with a32nx
2. After that i've deleted and installed installer again, but nothing new
3. I've checked files of game in steam.

**Expected behavior**

I wanted to play :3

**Additional context**

I don't think that only I have this problem

Discord username (if different from GitHub): dwarf#8888

**Comment by tracernz** [comment]
You should see FlyByWire A320 available in aircraft selection. Do not select Airbus A320, as that is the Asobo one included with the base game.
