### ISSUE TITLE
[BUG] Error when installing A32NX.

### ISSUE THREAD

**Issue by Valerich228** [flybywiresim/installer#261]
v1.2.0

When i try to install A32NX trough installer, it can't do it, and writes "Retrying Full Module". The same issue with installing trough marketplace in FS2020. It installs 7-30mb, and then stops installing and starts it again. If i download plane trough browser, it says me "Network Error" (can't properly translate it, but on russian it's written like "Ошибка Сети"). So, i need some help with it. I disabled windows defender (and all windows protection systems) and antivirus too. I tried to install it on flash drive on another PC and copy it to community folder on main PC, but FS2020 didn't recognise the plane. Also i tried to reinstall Windows 10, and it didn't help.

**To Reproduce**

1. Firstly i encountered this problem in marketplace.
2. Then i tried to install it trough installer, and browser. Problem still appeared.
3. I tried to install it to flash drive, but it didn't work. Also i tried to reinstall Windows 10, and it didn't help.

Of course normal installing of A32NX, because i tried to install it on another PC, and it worked well.

I don't think it's a bug, but i think you can help with that problem. Maybe i will attach other images, videos, etc later.

Discord username (if different from GitHub): адхщба#6200

**Comment by FoxtrotSierra6829** [comment]
You should be able to copy the `flybywire-aircraft-a320-neo` folder inside your community directory from one PC to another, just like you tried. This is the only place the aircraft gets installed to. If your download was complete on the other PC, the aircraft should be detected properly. Did you make sure to select the right aircraft? It is a separate aircraft from the default A320neo now.

About your connection errors, does that only happen on that specific PC?

**Comment by Valerich228** [comment]
No, it isn't detected. Also, that errors happen on that specific PC, but internet connection the same on tho PCs. WiFi drivers also the same.

**Comment by FoxtrotSierra6829** [comment]
All I can tell you is that it doesn't matter from which PC you downloaded it. If it doesn't show up, either the original download wasn't complete (try download via website for that purpose - if the zip opens, it's downloaded correctly), or you didn't insert it into the right place.

About the Wi-Fi issue - maybe try to get further towards the router or try to reconfigure the Wi-Fi after deleting it, but since you have a connection at all, it's unlikely to be an issue with your card or drivers.

**Comment by Valerich228** [comment]
I meant that both PC using same WiFi connection and drivers. But on one PC installation fails, on other - not fails. Maybe i can sent you logs of installer, but how i can do that?

**Comment by Valerich228** [comment]
When can i wait for answer?

**Comment by FoxtrotSierra6829** [comment]
You can send us logs by `CTRL+F12`, then right click on the console (bottom right), `Save as...`. Then upload it here.

But since you told us about general connection issues, I doubt we will find there anything. You should rather seek support e.g. via the Microsoft forums.

**Comment by Valerich228** [comment]
I mean, there is no connection issues here. Just mentioned that we connected to one wifi, and pcs both have same wifi driver installed.
[-1624169134892.log](https://github.com/flybywiresim/installer/files/6681812/-1624169134892.log)
There it is.

**Comment by Valerich228** [comment]
I think it is some protection system of a brwoser. How can i turn it off?

**Comment by FoxtrotSierra6829** [comment]
`45 [...] net::ERR_SSL_PROTOCOL_ERROR 200`

You've got an issue with the encrypted transmission of web data. Try these:

https://aboutssl.org/fix-google-chrome-error-err_ssl_protocol_error/
