### ISSUE TITLE
FBW installer problem

### ISSUE THREAD

**Issue by GamingLegend2007** [flybywiresim/installer#279]
### Installer Version

N/A

### Describe the bug

The installer loaded and came up with the error of having a problem with the folder.

### Expected behavior

To load the installer and download a32nx, this error came up and I have redownloaded it many times, hasn't happened before.

### Steps to reproduce

Downloaded the fbw installer off of website
Downloaded it
It loaded and came up with the error.

### References (optional)

![Screenshot (5)](https://user-images.githubusercontent.com/88375403/127992803-0eae6dda-5d2a-4d12-a4a9-29b15aff8434.png)

### Additional info (optional)

This was working before, I had to reinstall msfs and all the files for the reinstalled version are in the same drive and place.

### Discord Username (optional)

Gaming_Legend1#0399

**Comment by FoxtrotSierra6829** [comment]
Duplicate of #258
