### ISSUE TITLE
Installer crashes if MSFS is not installed

### ISSUE THREAD

**Issue by danscodelab** [flybywiresim/installer#281]
### Installer Version

1.2.0

### Describe the bug

When opening the Installer the TypeError `[ERR_INVALID_ARG_TYPE] The "path" argument must be a type of string. received undefined` occurs

### Expected behavior

Installer starts normally

### Steps to reproduce

1, Download the newest 20h2 build
2. Run the Installer

### References (optional)

![_err](https://user-images.githubusercontent.com/80229817/129567984-9ff1e2c7-e5e7-40eb-a1e1-576e4cc796ae.png)

### Discord Username (optional)

dan #0001

**Comment by FoxtrotSierra6829** [comment]
Can you confirm you tested it with different windows versions and the error is directly dependent on the windows version?

**Comment by danscodelab** [comment]
yes i tested it under different windows version / it only fails on the **latest** 20h2 and 19h2 builds

**Comment by FoxtrotSierra6829** [comment]
There has to be some other condition as the distributed installer is working fine for me on 22000.132, but I'm gonna look at it as I've got a similar issue with unbuilt versions recently

**Comment by danscodelab** [comment]
> There has to be some other condition as the distributed installer is working fine for me on 22000.132, but I'm gonna look at it as I've got a similar issue with unbuilt versions recently

rgr tried to figure out the issue by building the installer but since #205 is not merged yet i can't really help - viel glück!

**Comment by FoxtrotSierra6829** [comment]
So in fact I have the issue that when executing `npm run start` (run webpack) on the `electron-builder` branch, I get an issue just like above on a machine running Windows 11 (22000.132) whereas it doesn't throw an issue on another machine running Windows 10 21H1 (19043.1110)

**Comment by danscodelab** [comment]
> So in fact I have the issue that when executing `npm run start` (run webpack) on the `electron-builder` branch, I get an issue just like above on a machine running Windows 11 (22000.132) whereas it doesn't throw an issue on another machine running Windows 10 21H1 (19043.1110)

there seems to be a problem with the 21H2 build in general when it comes to webpack (at least for me / had similar issues after upgrading with my own projects ) 

i think the issue on the 19H2 [18363.1734] might be Independent to the issue mentioned above 

also after installing the 20H2 build (19043.1165) on another pc it still keeps crashing with the same issue

**Comment by FoxtrotSierra6829** [comment]
can you try this?
https://cdn.flybywiresim.com/installer/dev/FlyByWire_Installer_Setup.exe

**Comment by FoxtrotSierra6829** [comment]
So actually it seems this is an issue with the electron-store where we save settings and data that is necessary to keep even after a restart. In my case, on webpack, apparently, it couldn't get initiated as it should, and therefore it was corrupted. After replacing `%appdata%\Electron\config.json` (for webpack) with the file from `%appdata%\FlyByWire Installer\config.json` (for packaged application), it did load up correctly. Can you first try deleting `%appdata%\FlyByWire Installer\config.json` and see if it rebuilts correctly on the next start of the app?

**Comment by FoxtrotSierra6829** [comment]
Issue should be fixed now, try https://cdn.flybywiresim.com/installer/dev/FlyByWire_Installer_Setup.exe

**Comment by danisbored** [comment]
> Issue should be fixed now, try [Installer v2 dev build](https://cdn.flybywiresim.com/installer/dev/FlyByWire_Installer_Setup.exe)

is fixed
