### ISSUE TITLE
Discord link on GitHub landing page linked from installer does not work

### ISSUE THREAD

**Issue by mduft** [flybywiresim/installer#287]
### Installer Version

v2.0.0

### Describe the bug

Whn klicking the (!) icon top right, on the GitHub page landing on, there is a Discord link - this leads (me) to nowhere. It is not a server link, and Discord simply tells me that I'm "in a strange place" where no text and voice chats are available.

### Expected behavior

The link should probably be a server invite link, so I can join the server?

### Steps to reproduce

1. click (!) in the installer
2. click "Open" next to the discord link
3. Discord (web) opens and tells me I'm lost (after login - other servers and channels work).

**Comment by FoxtrotSierra6829** [comment]
The Link is correct, but only works if you're logged in and did already join the server. It's intended to lead you to the #support channel.
Invite link is: https://discord.gg/flybywire

**Comment by mduft** [comment]
I was fully aware of the situation you describe, and I did manage to join the server from a link from the homepage. Just wanted to point out that support-seekers which did not yet join the server and who are not developers or experts might have a ... suboptimal user experience since they land... nowhere.
