### ISSUE TITLE
Installer can't be installed...

### ISSUE THREAD

**Issue by forcebio** [flybywiresim/installer#289]
### Installer Version

v2.0.1

### Describe the bug

Hi,
Yesterday, I launch the updater, it download as always with no issue the new version of the A32NX version Dev.
In the main time, it pops that a new version of the installer was available, and that I have to restart. I do that, but Kaspersky detect a virus (UDS:Trojan-PSW.Win32.Stealer).
This mornig, new try... I download the Installer, try to launch it but I have an error : "Lancement bloqué pour Desktop application to Installe and Customize mod", and impossible to install the installer...
How to solve that ? My AV is Kaspersky...
Regards !

### Expected behavior

I hope I can install the installer :)

### Steps to reproduce

1. Launch the installer
2. 2. Error message

### Discord Username (optional)

forcebio#6130

**Comment by FoxtrotSierra6829** [comment]
Sorry, but the only thing I can do for you is to tell you it doesn't contain a virus ( check https://www.virustotal.com/gui/file/2b65b1fd5e91a0cf73c5ef72306d53fd67f8366dd6eb63daab32189301616deb , Kaspersky is the only one who flags it) and to disable Kaspersky for the installation or add an exception if possible.

**Comment by FoxtrotSierra6829** [comment]
Closing as it is currently not flagged by any antivirus anymore according to [virustotal](https://www.virustotal.com/gui/file/3fb1e2e2b0d77c4ff1a993ea0b10b06767b58b021d81a7cd373d2338fb899966/detection)
