### ISSUE TITLE
Error installer

### ISSUE THREAD

**Issue by ahaos** [flybywiresim/installer#307]
### Aircraft Version

Development

### Build info

```json
{
  "built": "2021-10-27T17:24:37+00:00",
  "ref": "master",
  "sha": "89fb275da47e2aac29d90889b58a6bb1ace74829",
  "actor": "aguther",
  "event_name": "manual"
}
```

### Describe the bug

Recently, the update using the installer hangs at the "Finishing update" stage. The installer's version is the latest. I am updating the development version. It started with the installation of Windows 11. If you forcefully interrupt and restart it, it completely pumps the plane and installs normally. When updating, glitches again.

### Expected behavior

Завершение установки

### Steps to reproduce

1. Run Update with the Dev-version installed and wait for the "Finishing update" stage

**Comment by FoxtrotSierra6829** [comment]
stale issue, please reopen if the issue is still existent
