### ISSUE TITLE
installing liveries problems

### ISSUE THREAD

**Issue by Bentebert** [flybywiresim/installer#310]
### Installer Version

2.0.1

### Description

Hi great support. How can i install liveries. version 2.0.1 installed. 
i copy the folder A32NX_A320_NEO_AtlanticAirways into the Community folder, but nothing happen when i start flybywire installer, the red liveries installer dosent comes up on the screen. 
I copyed the liveries to this folder: C:\Users\ebert\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community
What does i do wrong ?
Regards Bent Ebert 
ebert@danbbs.dk

**Comment by FoxtrotSierra6829** [comment]
As your folder name already contains "A32NX" I suspect it's already a livery for the A32NX? We only convert those liveries which have been created for the default A320neo.
