### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Hypeism** [flybywiresim/installer#317]
### Installer Version

1.2.0

### Description

Add an option to enable/disable automatic launch of the installer on PC startup

### Discord Username (optional)

◯[Z+85-∫₀⁹⁰secxsin²xdx/(1+secx)]

**Comment by FoxtrotSierra6829** [comment]
Partially duplicate of #105 , thus modifying this issue to only cover autostart

**Comment by ErickSharp** [comment]
This feature is coming in version 3 of the installer! 😊

**Comment by aighes** [comment]
Maybe it's a better idea to have a command-line switch. Like if you run FlyByWire Installer.exe --update_a32nx it won't start the gui of the installer but just show a progress bar and updates the A32nx based on the settings done before in the installer.

**Comment by ErickSharp** [comment]
> Maybe it's a better idea to have a command-line switch. Like if you run FlyByWire Installer.exe --update_a32nx it won't start the gui of the installer but just show a progress bar and updates the A32nx based on the settings done before in the installer.

I don't think that's necessarily something we are currently interested in doing. The whole point of our installer is to be a friendly GUI to make it easier for non-technical users to install their aircraft.
