### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by AllenJackson** [flybywiresim/installer#326]
### Installer Version

2.1.1

### Describe the bug

After loading the installer, a message in left hand Panel  Update available. However, in the centre panel the usual options to update the Stable, Development are NOT available.

Reinstalled the Installer but same problem.

### Expected behavior

Option to update either Stable or Development version

### Steps to reproduce

Open Installer

**Comment by FoxtrotSierra6829** [comment]
can you share a screenshot describing the issue please?

**Comment by AllenJackson** [comment]
It’s now working!!
From other posts I read on Discord appears GitHub May have been down for a while.
Anyway thanks for the reply
