### ISSUE TITLE
[BUG] Offline modal should not prevent usage

### ISSUE THREAD

**Issue by Benjozork** [flybywiresim/installer#33]
**Installer Version**
master

**Describe the bug**

The offline modal should not cover the whole UI. I might want to uninstall (or in the future switch local versions) even if offline.

![image](https://user-images.githubusercontent.com/4503241/103115354-3ebed380-4630-11eb-960e-48d308a09a7d.png)

Discord username (if different from GitHub): someperson#4953

**Comment by nistei** [comment]
Offline modal is completely disabled by now.
