### ISSUE TITLE
FBW heaquarter airport doesn´t show up in the installer

### ISSUE THREAD

**Issue by Ansgar142** [flybywiresim/installer#330]
### Installer Version

v2.2.0

### Describe the bug

it doesn´t show up the FBW headquarter airport in the installer

### Expected behavior

it should show up the FBW headquarter

### Steps to reproduce

i opened the FBW installer and on the lft side it should show up the headquarter airport

**Comment by FoxtrotSierra6829** [comment]
This is no bug, you just didn't find it
