### ISSUE TITLE
Install Button reagiert nicht

### ISSUE THREAD

**Issue by Stadei** [flybywiresim/installer#348]
### Installer Version

2.2.2

### Describe the bug

Nach dem Drücken auf Install, wird keine Datei heruntergeladen.

### Expected behavior

Download der Dateien

### Steps to reproduce

Installer gestartet
Install Button gedrückt.

Keine Reaktion

**Comment by FoxtrotSierra6829** [comment]
Hallo,
bitte lass uns den log zukommen, indem du
- das Debug tool mit `STRG+F12` öffnest
- oben im Menü `Console` suchst und anklickst
- irgendwo über dem log rechts clickst
- `Save as...` clickst und die Datei hier hochlädst

**Comment by Stadei** [comment]
Hallo, ich wollte noch dazusagen, dass ich den Flugsimulator wegen Platzmangels auf Laufwerk C  auf meinem zweiten Laufwerk E installiert habe.  GrussMichael Gesendet von Mail für Windows Von: Florian ScheunerGesendet: Samstag, 5. Februar 2022 19:33An: flybywiresim/installerCc: Stadei; AuthorBetreff: Re: [flybywiresim/installer] Install Button reagiert nicht (Issue #348) Hallo,bitte lass uns den log zukommen, indem dudas Debug tool mit STRG+F12 öffnestoben im Menü Console suchst und anklickstirgendwo über dem log rechts clickstSave as... clickst und die Datei hier hochlädst—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FoxtrotSierra6829** [comment]
Das macht überhaupt nichts, solange alles richtig konfiguriert ist, ist das ohne Probleme möglich

**Comment by gabryzano** [comment]
Ich hatte das gleiche Problem, ich habe es gelöst, indem ich den PC auf die Werkseinstellungen zurückgesetzt und MSFS 2020 neu installiert habe. Es war wahrscheinlich ein Windows-Problem

**Comment by FoxtrotSierra6829** [comment]
Closing due to outdated feedback. Please reopen if the error persists on the latest version
