### ISSUE TITLE
Failed to install Salty Mod

### ISSUE THREAD

**Issue by strongbow1** [flybywiresim/installer#373]
### Installer Version

v3.1.0

### Describe the bug

Failed to install Salty mod from the installer, keep getting notification something went wrong
![Untitled](https://user-images.githubusercontent.com/21293934/163703222-959d0dcb-287c-4488-a0f4-9a45acd8f87d.png)

### Expected behavior

To be able to install the Salty B747 Mod

### Steps to reproduce

Tried to install stable and development, both failed

### References (optional)

https://user-images.githubusercontent.com/21293934/163703489-97144853-fff3-4079-b382-1856dbb20e3f.mp4

**Comment by FoxtrotSierra6829** [comment]
can you retry and collect the logs as described [here](https://docs.flybywiresim.com/fbw-a32nx/installation/#installer-debug-logs) thereafter?

**Comment by strongbow1** [comment]
I solved it in the mean time. I had to uninstall the installer and then restart reinstall restart and then install the Salty mod. it worked. Was a bit to get it to work but I solved it. Something to look into that when you update the installer it corrupted some file and only with a fresh install it worked.
