### ISSUE TITLE
Installer doesn't start

### ISSUE THREAD

**Issue by skyline69** [flybywiresim/installer#376]
### Installer Version

v3.1.0

### Describe the bug

![image](https://user-images.githubusercontent.com/67526259/164984893-b029fde0-bbd6-4f3e-8990-50e0bc027042.png)
this is the bug.

### Expected behavior

The installer is usable?

### Steps to reproduce

1. Open FlyByWire Installer
2. get depression

### Discord Username (optional)

skyline#2760

**Comment by Benjozork** [comment]
this should be fixed now
