### ISSUE TITLE
Install Unavailable

### ISSUE THREAD

**Issue by kreimben** [flybywiresim/installer#378]
### Installer Version

3.1.0

### Describe the bug

I can't install anything with this installer.

### Expected behavior

Installer should install anything (a32nx, 737-8i..)

### Steps to reproduce

1. Download installer setup
2. Execute installer with admin privilege.
3. Select what I want to install
4. Can't install

### References (optional)

![image](https://user-images.githubusercontent.com/20333172/166131203-c79157ea-a6f7-40e5-a99f-323756702ad5.png)
![image](https://user-images.githubusercontent.com/20333172/166131211-a68d24b8-0060-444a-912a-d24f82dadf32.png)
![image](https://user-images.githubusercontent.com/20333172/166131217-1ee5582b-ecf2-4451-a99e-796253e12015.png)

### Additional info (optional)

I already re-installed this installer.

### Discord Username (optional)

Kreimben#7005

**Comment by FoxtrotSierra6829** [comment]
Can you run `Get-Process -Id (Get-NetTCPConnection -LocalPort 8380).OwningProcess` in Powershell and share a screenshot?

**Comment by kreimben** [comment]
![image](https://user-images.githubusercontent.com/20333172/166179316-7eed507f-2f1f-40e1-8cc8-34d66b5ea4ee.png)

**Comment by srior62929** [comment]
Hello. I'm also having this same problem. Everything I select is unavailable for download. I've tried to uninstall/reinstall the installer but the problem still persists.
