### ISSUE TITLE
Installer no longer working for me

### ISSUE THREAD

**Issue by StephN-B** [flybywiresim/installer#394]
### Installer Version

v 3.2.1

### Describe the bug

The installer is no longer working for me. In almost all screens, I get an 'Error' message in the bottom right corner, instead of the previous information:
![image](https://user-images.githubusercontent.com/87286233/182122653-9f6358c1-a0ac-45c8-ab02-0486e2b0e7b1.png)

I need to add that I am using BitDefender, and at some point (I don't recall the exact steps) Bitdefender decided to treat the Simbridge as Malware.

I have tried all of the following, either in isolation or combined, to get it to work again, none of these steps worked:
- Added exceptions for the installer and Simbridge to BitDefender
- Uninstalled, and reinstalled the FlyByWire installer
- Cleared the Registry
- Computer restart
- Temporarily disabling Bitdefender

### Expected behavior

Simple: I want to be able to again use the installer.
If there are certain steps I need to take to 'reset' my machine so that I can install the Installer from scratch, please let me know.
Also, if there are log files I can send you, happy to supply those.

### Steps to reproduce

I am a software tester myself, and I know how important these steps are.
But as I wasn't in 'testing mode', I didn't take note of the exact steps. Here is my best recollection:
1. I have BitDefender running on my Windows 10 machine
2. Updated Installer, which until this issue worked flawlessly, to latest Version
3. Downloaded latest A320 Neo Experimental version
4. Activated Simbridge
5. Had a test flight in MSFS, using the new map. All worked fine
6. Closed MSFS
From here it becomes 'scetchy':
7. Opened File explorer, navigated to Simbridge Folder within the Community Folder
8. Double clicked on the EXE file within this folder -> received message from BitDefender that Malware has been blocked.
9. Since then, I am having the issues mentioned above, and tried to remedy without success so far.

### Discord Username (optional)

StephN-B

**Comment by FoxtrotSierra6829** [comment]
Your internet connection seems to be unstable or there is an issue with your firewall

**Comment by StephN-B** [comment]
@FoxtrotSierra6829      
Hi there - all I can say: Bulls Eye!! Thank you.
It was the Firewall - once I opened it up all is working fine again.
Much appreciated! 
Oder: Vielen Dank!

**Comment by FoxtrotSierra6829** [comment]
Bitteschön!
