### ISSUE TITLE
[REQUEST] Ask for shortcut creation on desktop

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [flybywiresim/installer#40]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Ask the user if he wants to create a shortcut on the desktop.

**Additional context**
At the moment, the installer creates a shortcut on the desktop on every launch (if not existing). As I like to have my desktop clean, I am removing this each time I update the A32NX, which is a bit annoying. My Idea is to ask the user if he wants to create one or not. Maybe that could be asked the first time and then saved as a variable, that can be modified in settings menu.

Discord username (if different from GitHub): Foxtrot Sierra#6420

**Comment by nistei** [comment]
The shortcut is only created during the setup of the installer. You seem to be running the setup for the installer every time which creates the shortcut. Use the Windows start menu entry to start the installed application.

**Comment by FoxtrotSierra6829** [comment]
> 
> 
> The shortcut is only created during the setup of the installer. You seem to be running the setup for the installer every time which creates the shortcut. Use the Windows start menu entry to start the installed application.

Oh yes, you're right. I didn't see the shortcut and wasn't aware it's actually using the AppData directory as an install path for itself. My fault.
