### ISSUE TITLE
[REQUEST] Support installation of Working Title projects

### ISSUE THREAD

**Issue by groakley** [flybywiresim/installer#409]
### Installer Version

v3.3.2

### Description

In addition to FBW's A32NX, I'm also a huge fan of the Working Title CJ4. It would be great to be able to update all of my mods from the same installer. As far as I know WT does not provide their own installer, so updating the mod requires downloading a zip at the moment.

I would hope that resolving this would be as easy as [the PR](https://github.com/flybywiresim/installer/pull/371) to include Salty Simulations' 747. 

Thank you for the consideration! I can try to put together the PR myself, but first I wanted to check if this is something the FBW installer owners are even interested in, or if there's some obvious reason why this can't be done that I'm missing.

### References (optional)

* WT homepage: https://www.workingtitle.aero/packages/cj4/
* WT Github packages: https://github.com/Working-Title-MSFS-Mods/fspackages/

**Comment by FoxtrotSierra6829** [comment]
There has not been any interest shown from Working Title to come to our installer. As we don’t add any addon without the developers explicit wish, it’s currently unlikely to happen.

**Comment by groakley** [comment]
Bummer. I figured there was a reason. Thanks for the response.

**Comment by tracernz** [comment]
> Bummer. I figured there was a reason. Thanks for the response.

Check out the dev update stream today for the future of the CJ4. There is no need to carry it in our installer ;).
