### ISSUE TITLE
Error while installing: Unable to verify SSL certificate

### ISSUE THREAD

**Issue by hrmlsr** [flybywiresim/installer#413]
### Installer Version

3.3.3

### Describe the bug

![QQ图片20221220190909](https://user-images.githubusercontent.com/32532458/208659149-b5d626d0-a9c5-4797-bc4d-e196e217653e.png)
![QQ图片20221220190913](https://user-images.githubusercontent.com/32532458/208659155-d11ae5fa-d074-40e9-8969-ce3b2b1ff4c7.png)

### Expected behavior

unable to verify the first certificate

### Steps to reproduce

while install or update B747-8I and TSLTL Traffic Base Models

### References (optional)

tried reinstall，change VPN，change install directory，disable CDN cache，but doesn't work

### Discord Username (optional)

hrmlsr#8597

**Comment by Benjozork** [comment]
This is an isssue with your local SSL certificates on windows. Not sure we can do anything

**Comment by hrmlsr** [comment]
What should I do to fix SSL certificates?

**Comment by FoxtrotSierra6829** [comment]
On your PC, is the time synchronized by network (is set time automatically enabled) ? If not, enable that please

**Comment by hrmlsr** [comment]
The time synchronized successed by network with time.windows.com

**Comment by hrmlsr** [comment]
OK,I finally found the cause of the problem by myself.
