### ISSUE TITLE
What return this url

### ISSUE THREAD

**Issue by Jules010209** [flybywiresim/installer#416]
Hello, I don't know if I can put this here but I work with this launcher and I don't know what return this url (https://cdn.flybywiresim.com/addons/a32nx/stable) because when I would like open it there is a 404 error. Thanks you 👌

**Comment by FoxtrotSierra6829** [comment]
It is the base URL under which there are the files to download. The base URL isn't expected to return anything, you need to join it with the name of the file you want to get

**Comment by Jules010209** [comment]
Hey, thanks you, but what I do use (headers, body...) ?

**Comment by tracernz** [comment]
It might be useful to describe what you're trying to do.

**Comment by Jules010209** [comment]
Hey, I would like create an launcher who use the github releases, but in the "production.json" and "data.ts" there is an url and this url return a 404 error. In this files there are "key" and "url" so what I can put in this values ? Thanks you !
