### ISSUE TITLE
Community Directory same as Install directory

### ISSUE THREAD

**Issue by Creative-Difficulty** [flybywiresim/installer#443]
### Installer Version

v3.3.8

### Describe the bug

![grafik](https://github.com/flybywiresim/installer/assets/80907917/96941276-ad0e-48c1-8581-d4bd99616736)

### Expected behavior

It works

### Steps to reproduce

1. Install the installer

### Discord Username (optional)

immahead

**Comment by FoxtrotSierra6829** [comment]
I'm sorry, but I don't understand the issue, this seems to be working as intended? The two directories being individually defined values was introduced by #399 to accommodate for people who do not intend to use the community folder as their install location without interference of the installer functionality.
