### ISSUE TITLE
Issue with traffic not showing up

### ISSUE THREAD

**Issue by bobbywhite1958** [flybywiresim/installer#444]
### Installer Version

v3.3.8

### Describe the bug

In the FSLTL traffic injector section, when I hit start, the box appears on the screen, I hit "N" as I do not want to make any changes, the program connects to MSFS, however, the only line that appears is the following "KJFK using MAX 40 additional parked aircraft.  That's it, no more lines indicating what planes are flying, on the ground etc.  When I go to view mode, there are no aircraft on the tarmac's.   I've tried uninstalling and reinstalling, same result.  

### Expected behavior

For the program to work as it did in the past.

### Steps to reproduce

I Purchased a new computer, but kept my hard drive.  

### References (optional)

na

### Discord Username (optional)

1382

**Comment by FoxtrotSierra6829** [comment]
Please refer to https://www.fslivetrafficliveries.com/support-faq/ and [FSLTL Discord Server > #support-forum](https://discord.com/channels/781587165989175386/1022978356616118423)
