### ISSUE TITLE
Clean Installer reinstall

### ISSUE THREAD

**Issue by vmornar** [flybywiresim/installer#451]
### Installer Version

Latest

### Describe the bug

I installed Installer, SimBridge and A320NX, all was working ok. But at some point in time my Bitdefender antivirus quarantined some Installer files which I was unable to restore. Then I uninstalled Installer and reinstalled it, but ended with Installer in the state shown below, after several reinstalls and reboots. Nothing can be installed. How to start clean?

<img width="958" alt="image" src="https://github.com/flybywiresim/installer/assets/26645367/fe938fc2-8079-4093-b911-bbc7bcf535a7">

### Expected behavior

Installer to be working agai.

### Steps to reproduce

Cannot reproduce because I cannot start clean.

**Comment by FoxtrotSierra6829** [comment]
From the screenshot, the installer doesn't look like it is missing some files from the installation but instead that it cannot load files from the internet. Please check your internet connection, your anti virus for possible firewalls that prevent the installer from accessing the internet and potentially try a VPN.

**Comment by FoxtrotSierra6829** [comment]
Closing as stale. If the issue is still persistent, please reopen it.
