### ISSUE TITLE
Update via installer deletes files

### ISSUE THREAD

**Issue by FWB800** [flybywiresim/installer#469]
### Installer Version

v3.4.0

### Describe the bug

Simbridge failed to keep running. Autostart has stopped working. Manual start works then simbridge closes very quickly. I noticed  via the installer there was a simbridge update so ran that. Was unable to load coroutes so checked in resources and the coroutes folder was empty. I had 2 prevously save routes in there downloaded via the Simbrief Downloaded. They had been deleted.

### Expected behavior

It was working fine. Only thing I did was an Nvidia update, the whole msfs and FBW has gone buggy since that update

### Steps to reproduce

Autostart was still set to ON. Simbridge was not running.
Did manual start and watched task manager, simbridge started but used 4gb of memory then closed.

### References (optional)

![image](https://github.com/flybywiresim/installer/assets/158101912/5068166f-bee0-4a55-ba6f-3b3d4ae0aca8)

### Additional info (optional)

Yes it had been working fine, a few mins later it had failed, no mcdu and popouts hard to find.
[fbw-simbridge-2024-05-23-00.log](https://github.com/flybywiresim/installer/files/15418559/fbw-simbridge-2024-05-23-00.log)

### Discord Username (optional)

FWB800

**Comment by FoxtrotSierra6829** [comment]
closing in favor of https://github.com/flybywiresim/simbridge/issues/119
