### ISSUE TITLE
KFBW direct download

### ISSUE THREAD

**Issue by ItMeCorban** [flybywiresim/installer#479]
### Installer Version

any

### Description

Would love to take a look at KFBW but it seems locked behind the installer? Is there no manual download?

**Comment by FoxtrotSierra6829** [comment]
No, there is not currently. A direct download could be considered if there is demand of the community for this.

**Comment by Maximilian-Reuter** [comment]
I wouldnt say it is "locked" behind the installer. It is free afterall. you can download it through the installer and then delete the installer if you really want to

**Comment by ItMeCorban** [comment]
Not sure the installer runs under proton, though I haven't yet tried

**Comment by tracernz** [comment]
A brave soul! It is an electron app so it might have a reasonable chance. If you're really brave you could try build the installer natively on Linux.

**Comment by ItMeCorban** [comment]
Haha, I honestly thought simming on Linux would be a total pain but pretty much everything has worked as expected including the Thrustmaster airbus set! Being electron does give me confidence it'll just work. I'll give it a go and report back :)
