### ISSUE TITLE
[REQUEST] Change aircraft names on sidebar

### ISSUE THREAD

**Issue by wpine215** [flybywiresim/installer#54]
**Describe the feature you'd like to see implemented**

For consistency and licensing, change "A320neo" to "A32NX", and "A380" to "A380X"

**Additional context**

Discord username (if different from GitHub): Iceman#5540

**Comment by MisterChocker** [comment]
Also in this text
![image](https://user-images.githubusercontent.com/1857322/104139116-6ee4d100-53a9-11eb-9eec-5edd1c5b83a0.png)
