### ISSUE TITLE
[REQUEST] Make text not selectable

### ISSUE THREAD

**Issue by pepperoni505** [flybywiresim/installer#56]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

Currently you can select text on each page, which doesn't make sense to allow. It would make more sense to disable the ability to select text

**Additional context**

Discord username (if different from GitHub):

**Comment by FoxtrotSierra6829** [comment]
Second this.
It looks definitely quite odd when selected. At least the buttons text should not be selectable. Not sure about the description tho.

![grafik](https://user-images.githubusercontent.com/50082450/104700712-dd60c080-5714-11eb-897e-44919d428c1a.png)
