### ISSUE TITLE
[BUG] Not detecting installed version correctly

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/installer#58]
**Installer Version**
https://github.com/flybywiresim/installer/commit/2a6455b9ffbbf03484a793fe3280c8ca0d8842a6 (vmaster)

**Describe the bug**

It currently says ![image](https://user-images.githubusercontent.com/1857322/104139314-e9622080-53aa-11eb-93a5-fc7cf2874ac9.png) on every version I can select ![image](https://user-images.githubusercontent.com/1857322/104139331-026ad180-53ab-11eb-8ce8-1908627d63a2.png)

**To Reproduce**

1. Just downloaded the installer (first time)
2. Run the installer
3. Go to "A320Neo" tab

**Expected behavior**

To show only the currently installed version

**Additional context**

Discord username (if different from GitHub): DerL30N#3751

**Comment by Benjozork** [comment]
This is intended behavior. The installer prevents you from doing anything if you use git-based installs, since it assumes you do not want it breaking your git repo / symlink.

If you have counterarguments for this design choice, feel free to explain.

**Comment by MisterChocker** [comment]
Good point!
