### ISSUE TITLE
[REQUEST] Make Image Elements Undraggable

### ISSUE THREAD

**Issue by ErickSharp** [flybywiresim/installer#60]
**Is your feature request related to a problem? Please describe.**

Yes, the images are currently able to be dragged instead of "baked" onto the page. This consists of the drawings of the a320 and a380 on the installer tabs, and the engine variant drawing. 

**Describe the feature you'd like to see implemented**

Make image elements undraggable by the user.

**Additional context**

Discord username (if different from GitHub): Erick [Z-6]#6484

**Comment by pepperoni505** [comment]
This relates to #56
