### ISSUE TITLE
[REQUEST] Message background color

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/installer#62]
**Describe the feature you'd like to see implemented**

I'd like these messages to fit the dark theme.
So messages would also have a darkish background.
![image](https://user-images.githubusercontent.com/1857322/104146511-4f5ea000-53cb-11eb-846a-184a251c4438.png)

**Additional context**

Discord username (if different from GitHub): DerL30N#3751

**Comment by Benjozork** [comment]
Outdated as of c5bae7f390ae14b6f616cca9b814562b632d22e3
