### ISSUE TITLE
[REQUEST] Highlight currently installed version

### ISSUE THREAD

**Issue by MisterChocker** [flybywiresim/installer#63]
**Describe the feature you'd like to see implemented**

Highlight the currently used/installed version / or change it's background color.

Currently I have to switch between version to know which version or type I've installed, e.g. whether I've installed a stable version, or a development build.

Yes the installed version is selected on startup and draws the a white outline, but the outline only shows the currently selected version, not the currently installed/used one.

![image](https://user-images.githubusercontent.com/1857322/104146875-939e7000-53cc-11eb-86f6-27371c610724.png)
![image](https://user-images.githubusercontent.com/1857322/104146884-9dc06e80-53cc-11eb-8201-e63ad5f9b5b0.png)

So, if an update arrives, I actually no longer know which version I am actually using (apart from the fact that the launcher selects the currently installed one on startup)

Maybe something like this
![image](https://user-images.githubusercontent.com/1857322/104154314-e7b54e80-53e4-11eb-999a-2f16bc795fff.png)

A bit like discord does, just using our own colors
![image](https://user-images.githubusercontent.com/1857322/104154535-7033ef00-53e5-11eb-8310-2c0d31dead3f.png)

**Additional context**

Discord username (if different from GitHub): DerL30N#3751

**Comment by Benjozork** [comment]
I will figma this @ZigTag can you implement it
