### ISSUE TITLE
[BUG] Poor "MSFS OPENED" Detection

### ISSUE THREAD

**Issue by Snapmatics** [flybywiresim/installer#64]
### **Installer Version**
`VMaster - Latest`

### **Describe the bug**

_The detection to check if the game is closed is poor as you can bypass it and install/update whatever version you want with 2 clicks._

### **To Reproduce**

1. Launch MSFS
2. Go in the Installer and then switch to the Home Tab and then back to A32NX very fast.
3. Choose any other version and click Install/Update.

### **Expected behavior**

It should not let you install/update any other version and the detection should be happening while you are switching tabs as well.

### **Additional Context**

N/A

### Video
https://user-images.githubusercontent.com/43104362/104166521-9d8f9580-5403-11eb-85e7-343a29a3883f.mp4

**Discord Username:** `Snapmatics#2424`

**Comment by Benjozork** [comment]
This is resolved in master
