### ISSUE TITLE
[REQUEST] Change heading size

### ISSUE THREAD

**Issue by cianwhite** [flybywiresim/installer#65]
**Describe the feature you'd like to see implemented**
Change the heading size of the "Mainline Versions", "Experimental Versions" to match the size of headings like "Details" in the A32NX page of the installer.

**Additional context**
I believe matching the size of the headings will better represent the point of the installer, it can give the impressions that the details are more important than the downloads. I would suggest either making the "Details" heading smaller or the "Mainline versions" heading larger.

Discord username (if different from GitHub): Cian#3596

**Comment by Benjozork** [comment]
I feel like the size of the cards below it already give it importance

**Comment by nistei** [comment]
> I feel like the size of the cards below it already give it importance

I agree with that.

**Comment by FoxtrotSierra6829** [comment]
Closing, as this is feedback on an outdated version. For feedback on the current UI, please open a new issue.
