### ISSUE TITLE
[REQUEST] Mini description 

### ISSUE THREAD

**Issue by Awemeter** [flybywiresim/installer#67]
**Is your feature request related to a problem? Please describe.**

This is not related to a bug

**Describe the feature you'd like to see implemented**

When you select a mod version it would be cool if you could get a description of what is special about that version. For example, for the FBW version, it could say an experimental version of the a32nx that adds a more realistic Flybywire system to the aircraft.

**Additional context**

Discord username: Awemeter#7919

**Comment by Benjozork** [comment]
Good idea.
