### ISSUE TITLE
[REQUEST] Change home text layout 

### ISSUE THREAD

**Issue by Awemeter** [flybywiresim/installer#73]
**Is your feature request related to a problem? Please describe.**

Home text is formated weirdly. 

**Describe the feature you'd like to see implemented**

I feel that the letter A needs to be moved down a line.

**Additional context**

![2021-01-11 (5)_LI](https://user-images.githubusercontent.com/71922517/104254159-33e3ab80-5444-11eb-8efa-e04831d77cf3.jpg)

Discord username: Awemeter#7919

**Comment by pepperoni505** [comment]
Would you mind elaborating?

**Comment by Benjozork** [comment]
This is an issue on small window widths.

**Comment by FoxtrotSierra6829** [comment]
Moving to Backlog, as we currently do not show the Home tab
