### ISSUE TITLE
[BUG] Logo has a weird outline & it's small

### ISSUE THREAD

**Issue by Snapmatics** [flybywiresim/installer#78]
### **Installer Version**
`Vmaster - Latest`

### **Describe the bug**

Comparing to other icons, our installer has a weird outline/border and it's kind of small.

### **To Reproduce**

1. Search bar
2. Search the installer
3. You will see it there

### **Expected behavior**

It should be transparent in my opinion and bigger.

### **Additional context**

![image](https://user-images.githubusercontent.com/43104362/104303710-16a9ee00-54d3-11eb-9d2e-9328815795be.png)

Discord Username: `Snapmatics#0001`

**Comment by nistei** [comment]
![image](https://user-images.githubusercontent.com/1652722/104335140-6ac4ca80-54f3-11eb-810b-654ae15388f2.png)
The scaling issue does not occur in the start menu but only in the Windows search.

**Comment by Snapmatics** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1652722/104335140-6ac4ca80-54f3-11eb-810b-654ae15388f2.png)
> The scaling issue does not occur in the start menu but only in the Windows search.

![image](https://user-images.githubusercontent.com/43104362/104335748-605afe80-54fc-11eb-8b49-66d0b6f01cf5.png)
![image](https://user-images.githubusercontent.com/43104362/104335804-6a7cfd00-54fc-11eb-9cab-3f0fc0a0b8fc.png)

**Comment by ZigTag** [comment]
It looks like the logo we use is slightly too small

**Comment by FoxtrotSierra6829** [comment]
idk when we fixed it, but it's fixed, lol
