### ISSUE TITLE
[REQUEST] DROP-DOWN MENU  

### ISSUE THREAD

**Issue by FabioMike06** [flybywiresim/installer#89]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature you'd like to see implemented**

Edit the version history with a drop-down menu and make the latest stable version visible before opening the menu. Move the stable version before developer version

**Additional context**

![FlyByWire Installer 13_01_2021 08_32_57](https://user-images.githubusercontent.com/72151591/104421209-562c1500-557b-11eb-911c-3241adc8d7e7.png)

**Comment by MisterChocker** [comment]
@FabioMike06 please only request one change for one issue.

**Comment by MisterChocker** [comment]
btw duplicate of https://github.com/flybywiresim/installer/issues/59

**Comment by nistei** [comment]
> btw duplicate of #59

The dropdown here is for the version history. So instead of showing all versions only show the newest and the others in a dropdown. Issue #59 is about options for uninstalling etc.

**Comment by MisterChocker** [comment]
Well the example given was for uninstall, yes

**Comment by ExampleWasTaken** [comment]
I would change the version history to a list view. That way the current dot design could be maintained.

**Comment by FoxtrotSierra6829** [comment]
Closing, as this is feedback based on an outdated version. For feedback regarding the current UI, please open a new issue.
