### ISSUE TITLE
[REQUEST] IMPROVE PAGE SELECTION TAB AESTHETIC

### ISSUE THREAD

**Issue by ko-zone** [flybywiresim/installer#98]
**Is your feature request related to a problem? Please describe.**

I am currently installing the A32NX and I have gone to my settings page and the selection tab says it is uninstalled

![unknown (6)](https://user-images.githubusercontent.com/70115175/104652142-58988700-56c1-11eb-96ed-02f4adc88a03.png)
![unknown (5)](https://user-images.githubusercontent.com/70115175/104652148-5a624a80-56c1-11eb-8031-8be33d41979d.png)

**Describe the feature you'd like to see implemented**

So maybe it should say downloading with a small blue bar below it at the border between the A32NX and the A38X showing how much was been done with a bar concept and maybe even include a percentage value somewhere.

**Additional context**

Discord username (if different from GitHub): KO Zone#2134

**Comment by Benjozork** [comment]
done by #140
