### ISSUE TITLE
[REQUEST] A38X MISLEADING STATUS

### ISSUE THREAD

**Issue by ko-zone** [flybywiresim/installer#99]
**Is your feature request related to a problem? Please describe.**

The A38X is identified as "not installed"

![unknown (7)](https://user-images.githubusercontent.com/70115175/104653243-f50f5900-56c2-11eb-91a1-1d974367b848.png)

**Describe the feature you'd like to see implemented**

As the A38X isn't even released you can't really uninstall it let alone download it, maybe it should say something like "Coming Soon" to clarify that the aircraft is not out to avoid any sort of misinterpretation.

**Additional context**

Discord username (if different from GitHub): KO Zone#2134

**Comment by ko-zone** [comment]
Just realized someone else reported this.

**Comment by nistei** [comment]
Duplicate of #77
